wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/rmse
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid/loss
      5: 1
      6:
      - 1
    - 1: valid/rmse
      5: 1
      6:
      - 1
    python_version: 3.9.15
    start_time: 1674262882.183733
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 63
      - 74
      2:
      - 1
      - 9
      - 41
      - 55
      - 63
      - 74
      3:
      - 7
      - 13
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 1
      - 5
